In [1]:
#IMPORT LIBRARIES NECESSARY FOR DATA ANALYSIS
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt

In [2]:
#READ IN DATA 
df = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
#CHECK HEAD OF DATAFRAME
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
#i might come back to make a new dataset in other to balance the dataset
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [5]:
#LABEL ENCODE THE Y VARIABLE
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df.stabf = encoder.fit_transform(df.stabf)
#y_test.stabf = fit_transfrom()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  int32  
dtypes: float64(13), int32(1)
memory usage: 1.0 MB


In [7]:
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [8]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347      1  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957      0  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471      1  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871      1  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860      1

In [9]:
X = df.drop(columns=['stab','stabf'])
y = df['stabf']

In [10]:
X.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  
1 -1.255012  0.413441  0.862414  0.562139  0.781760  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  
4 -0.554305  0.797110  0.455450  0.656947  0.820923

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [12]:
x_train.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
2694  6.255995  2.542401  7.024714  9.476518  3.529888 -1.224881 -0.688228   
5140  5.070581  5.490253  8.075688  0.761075  4.220888 -1.280596 -1.902185   
2568  1.220072  8.804028  3.874283  8.433949  3.614027 -1.039236 -0.953566   
3671  7.498402  6.697603  8.798626  2.126236  3.134585 -1.581906 -0.589386   
7427  7.074006  1.337511  6.100756  7.759156  2.526922 -0.922540 -0.632600   

            p4        g1        g2        g3        g4  
2694 -1.616780  0.568221  0.618403  0.685739  0.660088  
5140 -1.038107  0.443515  0.097244  0.916955  0.129254  
2568 -1.621224  0.908353  0.923594  0.238881  0.660156  
3671 -0.963293  0.260826  0.899003  0.964752  0.600598  
7427 -0.971782  0.984580  0.716082  0.836928  0.165162

In [13]:
x_train.iloc[:, 0:4]

tau1      tau2      tau3      tau4
2694  6.255995  2.542401  7.024714  9.476518
5140  5.070581  5.490253  8.075688  0.761075
2568  1.220072  8.804028  3.874283  8.433949
3671  7.498402  6.697603  8.798626  2.126236
7427  7.074006  1.337511  6.100756  7.759156
...        ...       ...       ...       ...
2895  9.504984  5.265415  2.029617  8.026334
7813  8.035818  4.632548  1.177810  1.204950
905   7.052560  3.264057  1.405949  4.497549
5192  5.085242  1.790031  2.486392  2.848192
235   1.205354  6.995045  5.930860  2.523856

[8000 rows x 4 columns]

In [14]:
x_train

tau1      tau2      tau3      tau4        p1        p2        p3  \
2694  6.255995  2.542401  7.024714  9.476518  3.529888 -1.224881 -0.688228   
5140  5.070581  5.490253  8.075688  0.761075  4.220888 -1.280596 -1.902185   
2568  1.220072  8.804028  3.874283  8.433949  3.614027 -1.039236 -0.953566   
3671  7.498402  6.697603  8.798626  2.126236  3.134585 -1.581906 -0.589386   
7427  7.074006  1.337511  6.100756  7.759156  2.526922 -0.922540 -0.632600   
...        ...       ...       ...       ...       ...       ...       ...   
2895  9.504984  5.265415  2.029617  8.026334  3.449756 -0.922754 -1.526305   
7813  8.035818  4.632548  1.177810  1.204950  4.093208 -1.568218 -0.819966   
905   7.052560  3.264057  1.405949  4.497549  3.741358 -0.629026 -1.407945   
5192  5.085242  1.790031  2.486392  2.848192  3.159670 -0.892898 -1.025461   
235   1.205354  6.995045  5.930860  2.523856  5.230127 -1.755047 -1.567927   

            p4        g1        g2        g3        g4  
2694 -1.616780  0.568221  0.618403  0.685739  0.660088  
5140 -1.038107  0.443515  0.097244  0.916955  0.129254  
2568 -1.621224  0.908353  0.923594  0.238881  0.660156  
3671 -0.963293  0.260826  0.899003  0.964752  0.600598  
7427 -0.971782  0.984580  0.716082  0.836928  0.165162  
...        ...       ...       ...       ...       ...  
2895 -1.000696  0.191864  0.611297  0.080008  0.350312  
7813 -1.705024  0.223384  0.317770  0.726623  0.441620  
905  -1.704387  0.868306  0.605566  0.100591  0.747320  
5192 -1.241311  0.473917  0.418512  0.326253  0.982488  
235  -1.907153  0.861961  0.202768  0.848373  0.739993  

[8000 rows x 12 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
x_train

array([[ 0.36732671, -0.98604156,  0.65044706, ...,  0.33985949,
         0.58556788,  0.49223946],
       [-0.06465869,  0.08943734,  1.03507899, ..., -1.5584875 ,
         1.42964862, -1.44352101],
       [-1.46785   ,  1.29841758, -0.50253617, ...,  1.45153362,
        -1.04574277,  0.49248925],
       ...,
       [ 0.65760851, -0.72275633, -1.4058879 , ...,  0.29310048,
        -1.55058661,  0.81034412],
       [-0.05931596, -1.26053241, -1.01047147, ..., -0.38825455,
        -0.72678059,  1.66791568],
       [-1.47321368,  0.63843757,  0.25012249, ..., -1.17410957,
         1.179282  ,  0.78362657]])

In [18]:
x_test

array([[ 0.59395058, -0.41273345,  1.50392381, ...,  1.1672034 ,
        -1.50732963,  1.08472557],
       [ 0.2021896 ,  0.37441634, -0.18880047, ..., -0.39566024,
         1.41465051,  1.22601069],
       [-1.079044  , -0.31374544, -0.88463426, ..., -1.43849538,
         0.65182081, -1.6821675 ],
       ...,
       [ 0.94782488, -1.66372653, -1.65391963, ...,  0.12639128,
         0.57344494,  1.31934985],
       [-1.1202346 ,  0.19397855, -0.2378051 , ...,  0.79408717,
        -1.36232268, -0.80197116],
       [-1.37764025,  1.51186671,  0.28265058, ..., -0.91749729,
         0.00295027,  1.18902334]])

In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state= 1)
classifier.fit(x_train, y_train)

RandomForestClassifier(random_state=1)

In [20]:
y_pred = classifier.predict(x_test)
y_pred
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

array([1, 1, 0, ..., 0, 0, 1])

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 625   87]
 [  55 1233]]


0.929

In [22]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None]  

hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

grid_search = RandomizedSearchCV(estimator = classifier,
                           param_distributions = hyperparameter_grid,
                           scoring = 'accuracy',
                           cv = 5,
                           verbose = 1,
                           n_iter=10,      
                           n_jobs = -1,
                           random_state = 1)

In [32]:
grid_search = grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  2.5min finished


Best Accuracy: 91.88 %
Best Parameters: {'n_estimators': 1000, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2'}


In [33]:
#AFTER OBTAINING THE BEST PARAMETERS  PLUG THEM IN
learnclassifier = RandomForestClassifier(n_estimators= 1000,
                                         min_samples_split=2,
                                         min_samples_leaf=4,
                                         max_features = 'log2',
                                         random_state= 1)
learnclassifier.fit(x_train, y_train)

RandomForestClassifier(max_features='log2', min_samples_leaf=4,
                       n_estimators=1000, random_state=1)

In [34]:
yypred = learnclassifier.predict(x_test)
lmm = confusion_matrix(y_test, yypred)
print(lmm)
#ACCURACY OF BOOSTING
accuracy_score(y_test, yypred)

[[ 612  100]
 [  61 1227]]


0.9195

In [25]:
###EXBOOST CLASSIFIER
from xgboost import XGBClassifier
xclassifier = XGBClassifier(random_state=1)
xclassifier.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [26]:
ypred = xclassifier.predict(x_test)

In [27]:
#THIS IS THE CONFUSION MATRIX AFTER BOOSTING
cmm = confusion_matrix(y_test, ypred)
print(cmm)
#ACCURACY OF BOOSTING
accuracy_score(y_test, ypred)

[[ 648   64]
 [  45 1243]]


0.9455

In [40]:
##LIGHT GBM CLASSIFIER
from lightgbm import LGBMClassifier
LGclassifier = XGBClassifier(random_state=1)
LGclassifier.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [41]:
yLpred = LGclassifier.predict(x_test)
cmm = confusion_matrix(y_test, yLpred)
print(cmm)
#ACCURACY OF BOOSTING
accuracy_score(y_test, yLpred)

[[ 648   64]
 [  45 1243]]


0.9455